### ISSUE TITLE
README needs to outline ways to use it

### ISSUE THREAD

**Issue by mcmahonjohn** [bent/angular-json-validator#1]
The README doesn't outline the usage of this library as such, it's a mystery to new users how to use it. And most wouldn't bother after seeing little to no documentation.

**Comment by bent** [comment]
This project was an experiment and is not active. If you need to do basic JSON validation of responses from a RESTful API, I can only suggest that possibly a Swagger-based solution might be worth looking at.

**Comment by mcmahonjohn** [comment]
Thanks for the response. My project probably won't implement validating jsons just yet, but from what i saw in my search, this implementation looked promising. I'll look into Swagger-based solutions.
